name: Build GKI Kernel 5.10, 5,15 and 6.1

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
        description: Version
      BUILD_TYPE:
        required: true
        type: choice
        description: Build Type
        options:
          - BETA
          - REL
      FullLTO:
        required: false
        default: false
        type: boolean

jobs:
  build-kernel:
    name: Build Kernel
    strategy:
      matrix:
        include:
          - KERNEL_NAME: Pandora
            KERNEL_REPO: PandoraMTK/android_kernel_gki_5.10
            KERNEL_BRANCH: android12-5.10
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 19.1.5-20241130
          - KERNEL_NAME: Yuni
            KERNEL_REPO: PandoraMTK/android_kernel_gki_5.15
            KERNEL_BRANCH: android13-5.15
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 19.1.5-20241130
          - KERNEL_NAME: AngelBeats
            KERNEL_REPO: PandoraMTK/android_kernel_gki_6.1
            KERNEL_BRANCH: android14-6.1
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 19.1.5-20241130

    uses: ./.github/workflows/build_kernel_gki_common.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{matrix.KERNEL_NAME}}
      KERNEL_REPO: ${{matrix.KERNEL_REPO}}
      KERNEL_BRANCH: ${{matrix.KERNEL_BRANCH}}
      VERSION: ${{ matrix.VERSION }}
      BUILD_TYPE: ${{inputs.BUILD_TYPE}}
      FullLTO: ${{inputs.FullLTO}}
      COMPILER_VER: ${{matrix.COMPILER_VER}}
