name: Build GKI Kernels
run-name: Build GKI Kernels
on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        type: string
        description: Version
      BUILD_TYPE:
        required: true
        type: choice
        description: Build Type
        options:
          - BETA
          - REL
      BUILD_5_10:
        required: false
        type: boolean
        default: true
        description: Build 5.10
      BUILD_5_15:
        required: false
        type: boolean
        default: true
        description: Build 5.15
      BUILD_6_1:
        required: false
        type: boolean
        default: true
        description: Build 6.1
      BUILD_6_6:
        required: false
        type: boolean
        default: true
        description: Build 6.6
      FullLTO:
        required: false
        default: false
        type: boolean
      DEBUG:
        required: false
        default: false
        type: boolean
      UPDATE_CCACHE:
        required: false
        default: false
        type: boolean
jobs:
  init-build:
    name: Build Kernel
    strategy:
      fail-fast: false
      matrix:
        include:
          - KERNEL_NAME: Pandora
            IF: ${{inputs.BUILD_5_10}}
            KERNEL_REPO: PandoraMTK/android_kernel_gki_5.10
            KERNEL_BRANCH: android12-5.10
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 18.1.8-20250425
          - KERNEL_NAME: Yuni
            IF: ${{inputs.BUILD_5_15}}
            KERNEL_REPO: PandoraMTK/android_kernel_gki_5.15
            KERNEL_BRANCH: android13-5.15
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 20.1.4-20250505
          - KERNEL_NAME: AngelBeats
            IF: ${{inputs.BUILD_6_1}}
            KERNEL_REPO: PandoraMTK/android_kernel_gki_6.1
            KERNEL_BRANCH: android14-6.1
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 20.1.4-20250505
          - KERNEL_NAME: Haruhi
            IF: ${{inputs.BUILD_6_6}}
            KERNEL_REPO: PandoraMTK/android_kernel_gki_6.6
            KERNEL_BRANCH: android15-6.6
            VERSION: ${{ inputs.VERSION }}
            COMPILER_VER: 20.1.4-20250505
    uses: PandoraMTK/kernel_build_action/.github/workflows/build-gki-common.yml@main
    secrets: inherit
    with:
      KERNEL_NAME: ${{matrix.KERNEL_NAME}}
      NOSKIP: ${{matrix.IF}}
      KERNEL_REPO: ${{matrix.KERNEL_REPO}}
      KERNEL_BRANCH: ${{matrix.KERNEL_BRANCH}}
      VERSION: ${{ matrix.VERSION }}
      BUILD_TYPE: ${{inputs.BUILD_TYPE}}
      FullLTO: ${{inputs.FullLTO}}
      DEBUG: ${{inputs.DEBUG}}
      UPDATE_CCACHE: ${{inputs.UPDATE_CCACHE}}
      COMPILER_VER: ${{matrix.COMPILER_VER}}
